# Generated by Django 6.0.2 on 2026-02-28 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('bio', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(upload_to='profile/')),
                ('location', models.CharField(max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('github_link', models.URLField(max_length=50)),
                ('likedin', models.URLField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='technologies',
            field=models.TextField(blank=True, null=True),
        ),
    ]
